### ISSUE TITLE
Mp4 录制异常

### ISSUE THREAD

**Issue by Haha003** [youxiaochen/CameraMedia#1]
用demo中Mp4Activity录制的视频显示异常，像素乱码

**Comment by youxiaochen** [comment]
由于不知道您手机型号与相机硬件参数只能建议从下入手
1. 把裁剪功能去掉试一下看会不会乱码,&nbsp;如果去掉裁剪还会乱码就是手机的硬件参数可能不对,&nbsp;试着改一下硬件相关的参数MediaUtils,&nbsp; 如果不乱码那就是裁剪的功能有问题(可能性不大,用的Google)
2. 单独用H264Activity拍出来的试一下看H264数据会不会乱码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youxiaochen/CameraMedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 上午10:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[youxiaochen/CameraMedia] Mp4 录制异常 (Issue #1)





 
用demo中Mp4Activity录制的视频显示异常，像素乱码

**Comment by Haha003** [comment]
> 由于不知道您手机型号与相机硬件参数只能建议从下入手 1. 把裁剪功能去掉试一下看会不会乱码,&nbsp;如果去掉裁剪还会乱码就是手机的硬件参数可能不对,&nbsp;试着改一下硬件相关的参数MediaUtils,&nbsp; 如果不乱码那就是裁剪的功能有问题(可能性不大,用的Google) 2. 单独用H264Activity拍出来的试一下看H264数据会不会乱码
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "youxiaochen/CameraMedia" ***@***.***&gt;; 发送时间:&nbsp;2022年7月27日(星期三) 上午10:50 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[youxiaochen/CameraMedia] Mp4 录制异常 (Issue #1) 用demo中Mp4Activity录制的视频显示异常，像素乱码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的，好的，多谢，我研究研究 #
